name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.agoraweb.ro
        username: githubcicd@learn.dbbyte.com
        password: ${{ secrets.LEARN_PIPE }}

  # build:
  #   name: Build â›
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@main
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build dependencies
  #       run: npm run build
  #     - name: Archive production artifact
  #       uses: actions/upload-artifact@main
  #       with:
  #         name: dist
  #         path: dist
  # deploy:
  #   name: Deploy ğŸš€
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout repository
  #       uses: actions/checkout@main
  #     - name: Download artifact
  #       uses: actions/download-artifact@main
  #       with: 
  #         name: dist
  #         path: dist
  #     - name: Sync files to hosting
  #       uses: SamKirkland/FTP-Deploy-Action@4.0.0
  #       with: 
  #         server: ftp.agoraweb.ro
  #         username: githubcicd@learn.dbbyte.com
  #         password: ${{ secrets.LEARN_PIPE }}
